import { NextPage } from "next";
import { useSelect } from "react-supabase";
import DbUsers from "../components/dashboard/dbUsers";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Dashboard: NextPage = () => {
  const [{ count, data, error, fetching }, reexecute] = useSelect("user");

  if (error) return <div>{error.message}</div>;
  if (fetching) return <div>Loading users</div>;
  if (data?.length === 0) return <div>No users</div>;

  return (
    <div>
      <Head>
        <title>Database Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DbUsers />
      </main>
    </div>
  );
};

export default Dashboard;
